CREATE SEQUENCE USUARIO_SEQ
INCREMENT BY 1
MINVALUE 1
START WITH 1;

CREATE TABLE EASY_LIFE.USUARIO
(
    ID_USUARIO             BIGINT DEFAULT nextval('USUARIO_SEQ') PRIMARY KEY NOT NULL,
    NOME                   VARCHAR(100) NOT NULL,
    EMAIL                  VARCHAR(100) NOT NULL,
    SENHA                  VARCHAR(100) NOT NULL,
    DATA_CRIACAO           TIMESTAMP NULL,
    DATA_ATUALIZACAO       TIMESTAMP NULL
);