CREATE SEQUENCE PESSOA_SEQ
INCREMENT BY 1
MINVALUE 1
START WITH 1;

CREATE TABLE EASY_LIFE.PESSOA
(
    ID_PESSOA              BIGINT DEFAULT nextval('PESSOA_SEQ') PRIMARY KEY NOT NULL,
    NOME                   VARCHAR(100) NOT NULL,
    ATIVO                  BOOL NOT NULL,
    DATA_CRIACAO           TIMESTAMP NULL,
    DATA_ATUALIZACAO       TIMESTAMP NULL
);