CREATE SEQUENCE PERMISSAO_SEQ
INCREMENT BY 1
MINVALUE 1
START WITH 1;

CREATE SEQUENCE PERMISSAO_USUARIO_SEQ
INCREMENT BY 1
MINVALUE 1
START WITH 1;

CREATE TABLE PERMISSAO
(
    ID_PERMISSAO           BIGINT DEFAULT nextval('PERMISSAO_SEQ') PRIMARY KEY NOT NULL,
    DESCRICAO              VARCHAR(100) NOT NULL,
    DATA_CRIACAO           TIMESTAMP NULL,
    DATA_ATUALIZACAO       TIMESTAMP NULL
);

CREATE TABLE PERMISSAO_USUARIO
(
    ID_PERMISSAO_USUARIO BIGINT DEFAULT nextval('PERMISSAO_USUARIO_SEQ') PRIMARY KEY NOT NULL,
    ID_USUARIO BIGINT NOT NULL,
    ID_PERMISSAO BIGINT NOT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_PERMISSAO) REFERENCES PERMISSAO(ID_PERMISSAO)
);