INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_CADASTRAR_ESPACO', now(), null);
INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_PESQUISAR_ESPACO', now(), null);
INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_REMOVER_ESPACO', now(), null);

INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_CADASTRAR_PESSOA', now(), null);
INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_PESQUISAR_PESSOA', now(), null);
INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_REMOVER_PESSOA', now(), null);

INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_CADASTRAR_AGENDA', now(), null);
INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_PESQUISAR_AGENDA', now(), null);
INSERT INTO PERMISSAO (descricao, data_criacao, data_atualizacao) VALUES('ROLE_REMOVER_AGENDA', now(), null);


-- Administrador
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 1);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 2);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 3);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 4);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 5);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 6);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 7);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 8);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (1, 9);

-- Morador
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (2, 2);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (2, 5);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (2, 7);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (2, 8);
INSERT INTO PERMISSAO_USUARIO (ID_USUARIO, ID_PERMISSAO) values (2, 9);