CREATE SEQUENCE ESPACO_COMUM_SEQ
    INCREMENT BY 1
    MINVALUE 1
    START WITH 1;

CREATE TABLE ESPACO_COMUM
(
    ID_ESPACO_COMUM        BIGINT DEFAULT nextval('ESPACO_COMUM_SEQ') PRIMARY KEY NOT NULL,
    NOME                   VARCHAR(100) NOT NULL,
    ATIVO                  BOOL NOT NULL,
    HORARIO_INICIO         TIME NULL,
    HORARIO_FINAL          TIME NULL,
    DESCRICAO              VARCHAR(255) NULL,
    IMAGEM_UL              VARCHAR(255) NULL,
    MAXIMO_CONVIDADOS      INTEGER
);